import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :hardcorehandyman, HardcorehandymanWeb.Endpoint,
  url: [host: "hardcorehandyman.fly.dev", port: 443],
  check_origin: [
    "https://hardcorehandyman.fly.dev",
    "https://www.hardcorehandyman.fly.dev",
    "http://hardcorehandyman.fly.dev",
    "http://www.hardcorehandyman.fly.dev"
  ],
  # url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# force_ssl: [
#   host: nil,
#   rewrite_on: [:x_forwarded_port, :x_forwarded_proto],
#   # maybe true when we use this for real
#   hsts: false
# ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Hardcorehandyman.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
